# TODO: make it production ready
FROM node:16-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
#COPY package.json .
#COPY yarn.lock .
#RUN yarn install
# Copy app files
COPY . .
RUN yarn --network-timeout 100000
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]
