version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: planthub-db
    ports:
      - "5420:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - "docker.env"
volumes:
  dbdata: