version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: planthub-db
    user: root
    ports:
      - "5420:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - "docker.env"
    restart: always
  client:
    image: "orexinmaster/planthub-client:latest"
    container_name: planthub-client
    user: root
    ports:
      - "3000:3000"
    restart: unless-stopped
  server:
    image: "orexinmaster/planthub-server:latest"
    container_name: planthub-server
    user: root
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - /sys:/sys
      #- ./server/.env:/app/.env
      - ./test/.env:/app/.env
    devices:
      - /dev/mem:/dev/mem
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
volumes:
  dbdata: