version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: planthub-db
    user: root
    ports:
      - "5420:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - "docker.env"
    restart: always
  client:
    image: "tassilobalbo/planthub-client:latest"
    container_name: planthub-client
    user: root
    ports:
      - "80:80"
    volumes:
      - ./client/.env:/usr/share/nginx/html/.env
    restart: unless-stopped
  server:
    image: "tassilobalbo/planthub-server:latest"
    container_name: planthub-server
    user: root
    ports:
      - "5000:5000"
    volumes:
      - "/sys:/sys"
      - ./server/.env:/app/.env
    restart: always
volumes:
  dbdata: