version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: planthub-db
    ports:
      - "5420:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    env_file:
      - "docker.env"
    restart: always
volumes:
  dbdata: