version: '3'

services:
  db:
    image: "postgres:latest"
    container_name: planthub-db
    user: root
    ports:
      - "5420:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - "docker.env"
    restart: always
  #client:
  #  image: ""
  #  container_name: planthub-client
  #  user: root
  #  ports:
  #    - "3000:3000"
  #  restart: always
  server:
    image: "tassilobalbo/planthub-server"
    container_name: planthub-server
    user: root
    ports:
      - "5000:5000"
    restart: always
volumes:
  dbdata: